name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.14'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install Dependencies
      run: |
        corepack enable
        pnpm install
      env:
        CI: true

    - name: Build Project
      run: pnpm build

    - name: Run Tests
      run: pnpm test

    - name: Packaging
      run: |
        rm .gitignore
        cp LICENSE dist/
        cp README.md dist/
        cp package.json dist/
        mkdir -p dist/assets/ && cp assets/firemitt.svg dist/assets/

    - name: Setup Git Config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Checkout and update build branch
      run: |
        git push origin -d build &>/dev/null
        git checkout --orphan build
        rm -rf $(ls | grep -v dist)
        rm -rf .github
        mv dist/* .
        git add .
        git commit -m "Publish build"
        git push origin build